
\restrict iyJO4fkOruM78HWw9uLeaz7chGQ4cbTjghFjC3gUfWbGas1yGk5RmMBF6sx4vMl


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(150) NOT NULL,
    password character varying(150),
    yandex_id character varying(50),
    registration_type character varying(20) DEFAULT 'LOCAL'::character varying
);


ALTER TABLE public.users OWNER TO postgres;

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

COPY public.users (id, username, password, yandex_id, registration_type) FROM stdin;
1	morrasha	$2a$10$diFM9yfiL.KMt/oyWEZkxO0sKpAt.kWaNWtKSQvZW0CykcgYUQjX.	\N	\N
\.


SELECT pg_catalog.setval('public."User_id_seq"', 8, true);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_yandex_id_key UNIQUE (yandex_id);



\unrestrict iyJO4fkOruM78HWw9uLeaz7chGQ4cbTjghFjC3gUfWbGas1yGk5RmMBF6sx4vMl

